<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "rule".
 *
 * @property integer $id
 * @property string $class
 * @property array $data
 * @property integer $categoryId
 *
 * @property \app\models\category\Category $category
 * @property string $aliasModel
 */
abstract class Rule extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'rule';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['class', 'categoryId'], 'required'],
            [['data'], 'safe'],
            [['categoryId'], 'integer'],
            [['class'], 'string', 'max' => 255],
            [['categoryId'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\category\Category::class, 'targetAttribute' => ['categoryId' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'class' => 'Class',
            'data' => 'Data',
            'categoryId' => 'Category ID',
        ];
    }

    public function getCategory()
    {
        return $this->hasOne(\app\models\category\Category::class, ['id' => 'categoryId']);
    }




}
